---
# This is Playbook header. A playbook can have multiple plays
- name: Configure basic system parameters of Arista switches
  connection: network_cli
  hosts: all
  vars_files:
    - "{{inventory_dir}}/vault/secret.yml"

# Following secion describe tasks in form of Ansible modules. 
# A task has one or more ansible modules.
 
  tasks:
  - name: Configure username local priviledge 7
    eos_user:
      name: local
      privilege: 7
      configured_password: blahblah
      state: absent

  - name: Configure username for eAPI interface
    eos_user:
      name: eapiuser
      privilege: 15
      configured_password: icanttellyou
      state: present

  - name: Configure hostname, DNS server and domain name
    eos_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: fabric.example.com
      lookup_source: Management1
      name_servers: [8.8.8.8, 1.1.1.1]

  - name: Setup login banner.
    eos_banner: 
      banner: login
      text:  | 
             This is secure system. All login attempts are being logged.

  - name: Setup MOTD banner.
    eos_banner: 
      banner: motd
      text: |
            Hello and Welcome.

  - name: Setup syslog servers.
    eos_logging: 
      dest: host
      name: [10.0.2.2, 10.0.2.3]
      state: present

  - name: Configure local syslog buffer size.
    eos_logging:
      dest: buffered
      size: 4096

  - name: Configure severity level.
    eos_logging:
      dest: on
      level: informational
      state: present

  - name: Enable routing on all switches.
    eos_config:
      lines:
        - ip routing
        - ip multicast-routing
        - ipv6 unicast-routing  
        - router ospfv3
  - name: Configure loopbacks
    eos_config:
      lines:
        - description system loopback
        - ipv6 enable
      parents: interface loopback0
       
  - name: Prepare interfaces on spines.
    eos_config:
      lines:
        - no switchport
        - ipv6 enable
        - mtu 9000
        - ipv6 nd ra suppress all
        - ip pim sparse-mode
        - no shut
      parents: interface {{ item }}
    loop:
      - eth1
      - eth2
      - eth3
      - eth4
      - eth5
    when: '"spine" in inventory_hostname'

  - name: Prepare interfaces on leaves.
    eos_config:
      lines:
        - no switchport
        - ipv6 enable
        - mtu 9000
        - ipv6 nd ra suppress all
        - ip pim sparse-mode
        - no shut
      parents: interface {{ item }}
    loop:
      - eth1
      - eth2
      - eth3
    when: '"leaf" in inventory_hostname'


- import_playbook: lldp-2-config.yml
