---
- name: Open SSH channel and capture commands from Arista devices
  eos_command:
    commands:  "{{show_commands}}"
    # provider will be required only when using eapi as connection type in Asnible 2.5
    # provider: "{{cli}}"
  register: eos_output
  when: ansible_network_os == 'eos'

- name: Copy results into file
  blockinfile:
    marker: "********{{ item.1 }}**********"
    block: "{{ item.0 }}"
    dest: "{{inventory_dir}}/outputs/netsnapshot_{{timestamp.stdout}}/{{inventory_hostname}}.txt"
    create: true
  with_together: # Looping over two parallel sets of data.
     - "{{ eos_output.stdout }}"
     - "{{ show_commands }}"
  when: ansible_network_os == 'eos'
  delegate_to: localhost
